// Generated by gencpp from file tp_msgs/Sinus.msg
// DO NOT EDIT!


#ifndef TP_MSGS_MESSAGE_SINUS_H
#define TP_MSGS_MESSAGE_SINUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tp_msgs
{
template <class ContainerAllocator>
struct Sinus_
{
  typedef Sinus_<ContainerAllocator> Type;

  Sinus_()
    : header()
    , x(0.0)
    , y(0.0)  {
    }
  Sinus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::tp_msgs::Sinus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tp_msgs::Sinus_<ContainerAllocator> const> ConstPtr;

}; // struct Sinus_

typedef ::tp_msgs::Sinus_<std::allocator<void> > Sinus;

typedef boost::shared_ptr< ::tp_msgs::Sinus > SinusPtr;
typedef boost::shared_ptr< ::tp_msgs::Sinus const> SinusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tp_msgs::Sinus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tp_msgs::Sinus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tp_msgs::Sinus_<ContainerAllocator1> & lhs, const ::tp_msgs::Sinus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tp_msgs::Sinus_<ContainerAllocator1> & lhs, const ::tp_msgs::Sinus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tp_msgs::Sinus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tp_msgs::Sinus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tp_msgs::Sinus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tp_msgs::Sinus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tp_msgs::Sinus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tp_msgs::Sinus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tp_msgs::Sinus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b4d52af2aa98221d9bb260976d6a201";
  }

  static const char* value(const ::tp_msgs::Sinus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b4d52af2aa98221ULL;
  static const uint64_t static_value2 = 0xd9bb260976d6a201ULL;
};

template<class ContainerAllocator>
struct DataType< ::tp_msgs::Sinus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tp_msgs/Sinus";
  }

  static const char* value(const ::tp_msgs::Sinus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tp_msgs::Sinus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 x\n"
"float32 y\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::tp_msgs::Sinus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tp_msgs::Sinus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sinus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tp_msgs::Sinus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tp_msgs::Sinus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TP_MSGS_MESSAGE_SINUS_H
